"""Strategy repository contracts and in-memory implementation."""

from __future__ import annotations

from abc import ABC, abstractmethod

from packages.domain.domain.strategy.entities.rebalance_plan import RebalancePlan


class StrategyRepository(ABC):
    """Persistence boundary for strategy artifacts."""

    @abstractmethod
    def save_plan(self, plan: RebalancePlan) -> RebalancePlan:
        """Persist or update a rebalance plan."""

    @abstractmethod
    def get_plan(self, plan_id: str) -> RebalancePlan | None:
        """Load a rebalance plan by id."""

    @abstractmethod
    def list_plans(self, strategy_version_id: str) -> list[RebalancePlan]:
        """List plans generated by a strategy version."""


class InMemoryStrategyRepository(StrategyRepository):
    """Reference implementation used for unit tests and local wiring."""

    def __init__(self) -> None:
        self._plans: dict[str, RebalancePlan] = {}

    def save_plan(self, plan: RebalancePlan) -> RebalancePlan:
        self._plans[plan.plan_id] = plan
        return plan

    def get_plan(self, plan_id: str) -> RebalancePlan | None:
        return self._plans.get(plan_id)

    def list_plans(self, strategy_version_id: str) -> list[RebalancePlan]:
        return [
            plan
            for plan in self._plans.values()
            if plan.strategy_version_id == strategy_version_id
        ]
